name: gpa_cal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  sqflite: ^2.3.0
  # sqflite_common_ffi: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

fonts:
  - family: Ubuntu
    fonts:
      # - asset: fonts/Ubuntu-Regular.ttf
      - asset: fonts/Ubuntu-Bold.ttf
        weight: 700
      - asset: fonts/Ubuntu-Medium.ttf
        weight: 500
      - asset: fonts/Ubuntu-Regular.ttf
        weight: 400
      - asset: fonts/Ubuntu-MediumItalic.ttf
        weight: 400
      - asset: fonts/Ubuntu-MediumItalic.ttf
        weight: 400
      - asset: fonts/Ubuntu-Light.ttf
        weight: 300

flutter:
  uses-material-design: true
